### ISSUE TITLE
do we really need nim 1.2?

### ISSUE THREAD

**Issue by disruptek** [juancarlospaco/nim-bytes2human#2]
This requirement breaks https://github.com/disruptek/testes on nim-1.0 which breaks several other projects I have that I want to run on nim-1.0... Can you give me a tag on b3314ad04fa2f2948794f99d8f8158baebbb4a22 so I can deprecate?

**Comment by juancarlospaco** [comment]
Why your software wont run on `1.2` ?, I will revert back to `1.0`.

**Comment by disruptek** [comment]
It does run on 1.2.  I want it to run on 1.0 also.  You don't need to revert anything; I just want a tag to the old commit that I can point to as a requirement...

**Comment by juancarlospaco** [comment]
Nim `1.0` is supported.
